import {
  Grid,
  TextField,
  MenuItem,
} from "@mui/material";

import { Controller } from "react-hook-form";

function ReportsForm({
  control,
  errors,
}) {
  return (
    <Grid
      container
      spacing={2}
      mt={1}
    >
      <Grid item xs={12}>
        <Controller
          name="title"
          control={control}
          render={({ field }) => (
            <TextField
              {...field}
              fullWidth
              label="Report Title"
              error={!!errors.title}
              helperText={
                errors.title?.message
              }
            />
          )}
        />
      </Grid>

      <Grid item xs={12} md={6}>
        <Controller
          name="type"
          control={control}
          render={({ field }) => (
            <TextField
              {...field}
              select
              fullWidth
              label="Report Type"
            >
              <MenuItem value="Risk">
                Risk
              </MenuItem>

              <MenuItem value="Vendor">
                Vendor
              </MenuItem>

              <MenuItem value="Compliance">
                Compliance
              </MenuItem>

              <MenuItem value="Audit">
                Audit
              </MenuItem>

              <MenuItem value="Security">
                Security
              </MenuItem>

              <MenuItem value="Procurement">
                Procurement
              </MenuItem>

              <MenuItem value="Finance">
                Finance
              </MenuItem>

              <MenuItem value="Privacy">
                Privacy
              </MenuItem>

              <MenuItem value="Infrastructure">
                Infrastructure
              </MenuItem>

              <MenuItem value="Executive">
                Executive
              </MenuItem>

            </TextField>
          )}
        />
      </Grid>

      <Grid item xs={12} md={6}>
        <Controller
          name="generatedBy"
          control={control}
          render={({ field }) => (
            <TextField
              {...field}
              fullWidth
              label="Generated By"
              error={!!errors.generatedBy}
              helperText={
                errors.generatedBy?.message
              }
            />
          )}
        />
      </Grid>

      <Grid item xs={12} md={6}>
        <Controller
          name="generatedDate"
          control={control}
          render={({ field }) => (
            <TextField
              {...field}
              fullWidth
              type="date"
              label="Generated Date"
              InputLabelProps={{
                shrink: true,
              }}
              error={!!errors.generatedDate}
              helperText={
                errors.generatedDate?.message
              }
            />
          )}
        />
      </Grid>

      <Grid item xs={12} md={6}>
        <Controller
          name="status"
          control={control}
          render={({ field }) => (
            <TextField
              {...field}
              select
              fullWidth
              label="Status"
            >
              <MenuItem value="Generated">
                Generated
              </MenuItem>

              <MenuItem value="Scheduled">
                Scheduled
              </MenuItem>

              <MenuItem value="Failed">
                Failed
              </MenuItem>

            </TextField>
          )}
        />
      </Grid>

      <Grid item xs={12}>
        <Controller
          name="downloads"
          control={control}
          render={({ field }) => (
            <TextField
              {...field}
              fullWidth
              type="number"
              label="Downloads"
              error={!!errors.downloads}
              helperText={
                errors.downloads?.message
              }
            />
          )}
        />
      </Grid>

    </Grid>
  );
}

export default ReportsForm;