import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
} from "@mui/material";

import { useEffect } from "react";

import { useForm } from "react-hook-form";

import { yupResolver } from "@hookform/resolvers/yup";

import * as yup from "yup";

import ReportsForm from "./ReportsForm";

const schema = yup.object({

  title: yup
    .string()
    .required("Report Title is required"),

  type: yup
    .string()
    .required("Report Type is required"),

  generatedBy: yup
    .string()
    .required("Generated By is required"),

  generatedDate: yup
    .string()
    .required("Generated Date is required"),

  status: yup
    .string()
    .required("Status is required"),

  downloads: yup
    .number()
    .typeError("Downloads must be a number")
    .min(0, "Downloads cannot be negative")
    .required("Downloads is required"),

});

function ReportsDialog({
  open,
  onClose,
  onSave,
  selected,
}) {

  const {
    control,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm({

    resolver: yupResolver(schema),

    defaultValues: {

      title: "",

      type: "Risk",

      generatedBy: "",

      generatedDate: "",

      status: "Generated",

      downloads: 0,

    },

  });

  useEffect(() => {

    if (selected) {

      reset(selected);

    } else {

      reset({

        title: "",

        type: "Risk",

        generatedBy: "",

        generatedDate: "",

        status: "Generated",

        downloads: 0,

      });

    }

  }, [selected, reset]);

  return (

    <Dialog
      open={open}
      onClose={onClose}
      fullWidth
      maxWidth="md"
    >

      <DialogTitle>

        {selected
          ? "Edit Report"
          : "Add Report"}

      </DialogTitle>

      <form
        onSubmit={handleSubmit(onSave)}
      >

        <DialogContent>

          <ReportsForm
            control={control}
            errors={errors}
          />

        </DialogContent>

        <DialogActions>

          <Button
            onClick={onClose}
          >
            Cancel
          </Button>

          <Button
            variant="contained"
            type="submit"
          >
            {selected
              ? "Update"
              : "Save"}
          </Button>

        </DialogActions>

      </form>

    </Dialog>

  );

}

export default ReportsDialog;